language: rust
sudo: required
os: linux

compiler:
  - clang

cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - gcc
      - g++
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
    - os: windows
  fast_finish: true
  include:
    - os: osx
      sudo: required
    - os: windows
      sudo: required

before_install:
  - rustup self update
  - rustup component add rustfmt-preview

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./ci/install_capnp.sh && ./ci/install_capnp.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./ci/install_capnp.sh && ./ci/install_capnp.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install capnproto; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then source ./ci/set_path.sh; fi
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - cargo install capnpc || echo "capnpc already installed"
  - cargo install-update -a

script:
  - cargo fmt --all -- --check
  - cargo build && cargo test

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo coverage --exclude-pattern '/toshi/src/bin,/src/bin,/bin,/target' && bash <(curl -s https://codecov.io/bash) -s target/kcov; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo coveralls --exclude-pattern '/toshi/src/bin,/src/bin,/bin,/target'; fi
