host = "127.0.0.1"
port = 8081
path = "data/"
writer_memory = 200000000
log_level = "info"
json_parsing_threads = 4
bulk_buffer_size = 10000
auto_commit_duration = 10
experimental = true

[experimental_features]
leader = false
id = 2
nodes = ["127.0.0.1:8080"]

[merge_policy]
kind = "log"
min_merge_size = 8
min_layer_size = 10_000
level_log_size = 0.75
