host = "localhost"
port = 8080
path = "data/"
writer_memory = 8000000000
log_level = "info"
json_parsing_threads = 12
bulk_buffer_size = 0
auto_commit_duration = 10
enable_clustering = false

[merge_policy]
kind = "log"
min_merge_size = 8
min_layer_size = 10_000
level_log_size = 0.75
